version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - /host_mnt/c/Users/User/Projects/IP_Proooject/public:/var/www/html
    environment:
      - APP_ENV=development
